"use client";
import { useState } from "react";
import { useQueryClient } from "@tanstack/react-query";
import { Download, Upload } from "lucide-react";
import { api } from "@/lib/api";
import { Alert } from "./ui/Alert";

export function CsvImportPreview() {
  const [preview, setPreview] = useState<any>(null); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const qc = useQueryClient();
  const choose = async (file?: File) => { if (!file) return; setBusy(true); setError(""); const form = new FormData(); form.append("file", file); try { setPreview((await api.post("/restricted-list/import/preview", form, { headers: { "Content-Type": "multipart/form-data" } })).data); } catch (e: any) { const detail = e.response?.data?.detail; setError(Array.isArray(detail) ? detail.map((x: any) => `Linha ${x.line}: ${x.message}`).join(" · ") : detail ?? "CSV inválido"); } finally { setBusy(false); } };
  const apply = async () => { setBusy(true); try { await api.post("/restricted-list/import/apply", preview); setPreview(null); qc.invalidateQueries({ queryKey: ["restricted-list"] }); } catch (e: any) { setError(e.response?.data?.detail ?? "Falha ao aplicar CSV"); } finally { setBusy(false); } };
  const download = async () => { const response = await api.get("/restricted-list/export.csv", { responseType: "blob" }); const url = URL.createObjectURL(response.data); const link = document.createElement("a"); link.href = url; link.download = "restricted-list.csv"; link.click(); URL.revokeObjectURL(url); };
  return <section className="card mb-6 p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-sm font-semibold text-slate-900">Lista restrita</h2><p className="mt-1 text-xs text-slate-500">Importação UTF-8 em modo merge, com preview e aplicação atômica.</p></div><div className="flex gap-2"><button onClick={download} className="btn-ghost border border-slate-200 text-sm"><Download size={14} />Exportar CSV</button><label className="btn-secondary cursor-pointer text-sm"><Upload size={14} />Selecionar CSV<input type="file" accept=".csv,text/csv" className="sr-only" onChange={e => choose(e.target.files?.[0])} /></label></div></div>{error && <Alert variant="error" className="mt-4">{error}</Alert>}{busy && <p className="mt-4 text-sm text-slate-500">Validando…</p>}{preview && <div className="mt-5"><div className="overflow-x-auto rounded-lg border"><table><thead><tr><th>Linha</th><th>Identifier</th><th>Nome</th><th>Ativo</th><th>Ação</th></tr></thead><tbody>{preview.rows.map((row: any) => <tr key={row.line}><td className="px-4 py-3">{row.line}</td><td className="px-4 py-3 font-mono">{row.identifier}</td><td className="px-4 py-3">{row.name}</td><td className="px-4 py-3">{row.active ? "Sim" : "Não"}</td><td className="px-4 py-3 font-mono text-xs font-semibold">{row.action}</td></tr>)}</tbody></table></div><div className="mt-4 flex justify-end gap-2"><button onClick={() => setPreview(null)} className="btn-ghost">Cancelar</button><button onClick={apply} disabled={busy} className="btn-primary">Aplicar {preview.rows.length} linhas</button></div></div>}</section>;
}
